-- Sendy AI - Enhanced Supabase Schema setup

-- 1. Profiles Table (Stores all extracted resume data)
CREATE TABLE profiles (
    id TEXT PRIMARY KEY, -- This will be the Google User ID
    name TEXT,
    email TEXT,
    phone TEXT,
    university JSONB, -- Stored as array/list
    degree JSONB,     -- Stored as array/list
    designition JSONB, -- Stored as array/list (legacy)
    experiences JSONB, -- Stored as array of objects (Title, Company, Dates, Desc)
    skills JSONB,     -- Stored as array/list
    total_exp NUMERIC,
    raw_summary TEXT, -- Finalized summary after user edit
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE usage_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT REFERENCES profiles(id),
    action TEXT DEFAULT 'generate_email',
    model TEXT,
    provider TEXT,   -- e.g. 'hunter'
    success BOOLEAN DEFAULT TRUE,
    metadata JSONB, -- Additional details (e.g. linkedin_url)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE usage_logs ENABLE ROW LEVEL SECURITY;
