-- Sendy AI - Enhanced Supabase Schema setup

-- 1. Profiles Table (Stores all extracted resume data)
CREATE TABLE profiles (
    id TEXT PRIMARY KEY, -- This will be the Google User ID
    name TEXT,
    email TEXT,
    phone TEXT,
    university JSONB, -- Stored as array/list
    degree JSONB,     -- Stored as array/list
    designition JSONB, -- Stored as array/list (note: 'designition' as per library output)
    skills JSONB,     -- Stored as array/list
    total_exp NUMERIC,
    raw_summary TEXT, -- Finalized summary after user edit
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Usage Logs Table
CREATE TABLE usage_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT REFERENCES profiles(id),
    action TEXT DEFAULT 'generate_email',
    model TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE usage_logs ENABLE ROW LEVEL SECURITY;
