CREATE TABLE profiles (
    id TEXT PRIMARY KEY, -- This will be the Google User ID
    name TEXT,
    email TEXT,
    phone TEXT,
    university JSONB,
    degree JSONB,
    experiences JSONB,
    skills JSONB,
    total_exp NUMERIC,
    raw_summary TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE usage_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT REFERENCES profiles(id),
    action TEXT DEFAULT 'generate_email',
    date_accessed TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE usage_logs ENABLE ROW LEVEL SECURITY;
